"""LLM Synthesizer — merge scraped data into a USER.md."""

from __future__ import annotations

import litellm

from llmkit import LLMConfig
from whoami.models import ScrapedData

_SYSTEM_PROMPT = """\
你是 ProfileForge，一个 USER.md 生成器。

任务：根据以下用户的公开信息，生成适用于 AI 助理的用户画像。

规则：
1. 必须包含固定骨架：Name, Aliases, Timezone, Language, Summary
2. 根据实际数据自主决定额外 Section（不限数量和类型）
3. 禁止生成空字段或占位符
4. 每个字段必须对 AI 助理有实际交互价值
5. 语气是"对 AI 说的"（"User prefers..."），不是对人说的
6. 生成 Interaction Guidelines 告诉 AI 怎么与这个人交流
7. Markdown 格式，简洁有力
8. 过滤敏感信息（邮箱、手机号、身份证号等）
9. 根据信息量自行决定输出长度，信息少则精简，信息多则适当展开，但绝对不超过 30 行
10. 用短句和关键词，不要写段落
"""


def _build_user_prompt(data_list: list[ScrapedData]) -> str:
    parts: list[str] = []
    for data in data_list:
        section = f"### {data.platform}"
        if data.username:
            section += f" (@{data.username})"
        section += f"\nSource: {data.source_url}\n"
        if data.bio:
            section += f"Bio: {data.bio}\n"
        for item in data.items:
            section += f"- [{item.category}] {item.key}: {item.value}\n"
        parts.append(section)
    return "用户的公开信息：\n---\n" + "\n".join(parts) + "\n---\n\n请生成 USER.md："


async def synthesize(
    data_list: list[ScrapedData],
    *,
    llm: LLMConfig | None = None,
) -> str:
    """Call LLM to synthesize scraped data into USER.md content."""
    if not data_list:
        return "# USER.md\n\n_No data collected._\n"

    if llm is None:
        llm = LLMConfig()

    user_prompt = _build_user_prompt(data_list)
    kwargs = llm.to_litellm_kwargs()
    kwargs.update({
        "messages": [
            {"role": "system", "content": _SYSTEM_PROMPT},
            {"role": "user", "content": user_prompt},
        ],
        "temperature": 0.7,
        "max_tokens": 4096,
    })
    response = await litellm.acompletion(**kwargs)
    content: str = response.choices[0].message.content or ""
    # Strip markdown code fences if the LLM wraps the output
    if content.startswith("```"):
        lines = content.split("\n")
        lines = lines[1:]  # remove opening fence
        if lines and lines[-1].strip() == "```":
            lines = lines[:-1]
        content = "\n".join(lines)
    return content.strip() + "\n\n_Generated by whoami v0.1.0_\n"
